#!/bin/bash

# MIT License
# -----------
# Copyright (c) 2021 Karl Liang
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

usage() {
    local name
    name="$1"

    cat << USAGE
NAME:

    $name - a helper script for MTK build system.

SYNOPSIS:

    $name [-k|k|kernel] [-v|v|vendor] [-s|s|system]
    $name [-m|m|merge] [-mo|mo|merge-ota]
    $name [-ak|ak|add-kernel config] [-av|av|add-vendor config] [-as|as|add-system config]
    $name [-l|l|list]

DESCRIPTION:

    k, v, s - compile kernel, vendor or system

    m - execute MTK sign script to generate whole images for flash tool

    d - load build.conf setup

    ak, av, as - add lunch config of kernel, vendor or system, this option wouldn't
                 lunch config actually, only recording the config name. These lunch
                 configs would be activated when 'k' 'v' or 's' options is added.

    l - list current config and output dir location. Output dir only appreared after
        compile source codes.

EXAMPLE:

    $ $name ak vnd_qbert-userdebug     # add kernel config
    $ $name l          # show config and output info
    $ $name k v s m    # compile kernel, vendor, system and merge images

USAGE
}

enter() {
    local cmd_list
    local cmd ret i

    cmd_list=("$@")
    ret=0
    for((i = 0; i < ${#cmd_list[@]}; i++)); do
        cmd=${cmd_list[$i]}
        echo "$cmd"
        eval $cmd || {
            ret=$?
            echo "failed at: $cmd" >&2
            break
        }
    done

    return $ret
}

split_build() {
    local split_build merged_dir
    local argv cmd

    if [ "$kernel_out_dir" == "" ]; then
        lunch $kernel_lunch || return $?
    fi
    if [ "$vendor_out_dir" == "" ]; then
        lunch $vendor_lunch || return $?
    fi
    if [ "$system_out_dir" == "" ]; then
        lunch $system_lunch || return $?
    fi

    argv="$1"
    merged_dir="$(readlink -f final-images)"
    split_build=$system_out_dir/images/split_build.py

    rm -rf $merged_dir
    cmd="python $split_build"
    cmd+=" --system-dir $system_out_dir/images"
    cmd+=" --vendor-dir $vendor_out_dir/images"
    cmd+=" --kernel-dir $kernel_out_dir/images"
    cmd+=" --output-dir $merged_dir"
    cmd+=" ${argv}"

    enter "$cmd"
    return $?
}

build_image() {
    local cmd_list

    cmd_list=()
    argv="$1"
    case "$argv" in
        k|-k|kernel)
            cmd_list+=("lunch $kernel_lunch")
            cmd_list+=('kernel_out_dir=$ANDROID_PRODUCT_OUT')
            cmd_list+=('rm -rf ${kernel_out_dir}/obj/KERNEL_OBJ')
            cmd_list+=('rm -rf ${kernel_out_dir}/images/krn*')
            cmd_list+=("make -j24 krn_images")
            if [[ -e "$(readlink -e "$kernel_dir")" ]]; then
                cmd_list+=("setup_kernel_cmddb $kernel_dir")
            fi
            ;;
        s|-s|system)
            cmd_list+=("lunch $system_lunch")
            cmd_list+=('system_out_dir=$ANDROID_PRODUCT_OUT')
            cmd_list+=('rm -rf ${system_out_dir}/obj')
            cmd_list+=('rm -rf ${system_out_dir}/images')
            cmd_list+=("make -j24 sys_images")
            cmd_list+=("create_cmd_db system")
            ;;
        v|-v|vendor)
            cmd_list+=("lunch $vendor_lunch")
            cmd_list+=('vendor_out_dir=$ANDROID_PRODUCT_OUT')
            # avoid to remove kernel obj with same config name
            cmd_list+=('rm -rf ${vendor_out_dir}/obj/!(KERNEL_OBJ)')
            cmd_list+=('rm -rf ${vendor_out_dir}/images/vnd*')
            cmd_list+=("make -j24 vnd_images")
            cmd_list+=("create_cmd_db vendor")
            ;;
    esac

    enter "${cmd_list[@]}" || return $?
}

# Assume user has sourced envsetup.sh
mtk-make() {
    local -r build_conf='build.conf'
    local cmd_list
    local argv
    local -i timer

    if (( $# == 0 )); then
        usage $FUNCNAME
        return 1
    fi

    if [[ ! -z "$(declare -F lunch)" ]]; then
        # FIXME: need to complete cmd before exe mtk-make
        complete -F _lunch mtk-make
    elif [[ -f build/envsetup.sh ]]; then # no lunch func
        source build/envsetup.sh
    fi

    kernel_lunch=${kernel_lunch:-vnd_tb8173p1_64_bsp-userdebug}
    vendor_lunch=${vendor_lunch:-vnd_tb8173p1_64_bsp-userdebug}
    system_lunch=${sys_lunch:-sys_mssi_t_64_ab-userdebug}

    cmd_list=()
    while (( $# != 0 )); do
        argv="$1"
        case "$argv" in
            ak|-ak|add-kernel)
                shift
                kernel_lunch="$1"
                kernel_out_dir=''
                echo "kernel lunch added: $kernel_lunch"
                ;;
            av|-av|add-vendor)
                shift
                vendor_lunch="$1"
                vendor_out_dir=''
                echo "vendor lunch added: $vendor_lunch"
                ;;
            as|-as|add-system)
                shift
                system_lunch="$1"
                system_out_dir=''
                echo "system lunch added: $system_lunch"
                ;;
            d|-d|default)
                if [[ -e "$build_conf" ]]; then
                    source $build_conf
                fi
                ;;
            k|-k|kernel|\
            s|-s|system|\
            v|-v|vendor)
                cmd_list+=("build_image $argv")
                ;;
            m|-m|merge)
                cmd_list+=("split_build")
                ;;
            o|-o|ota)
                cmd_list+=("split_build --otapackage")
                ;;
            l|-l|list)
                if [[ -z "$kernel_out_dir" ]]; then
                    lunch $kernel_lunch 2>&-
                    kernel_out_dir=$ANDROID_PRODUCT_OUT
                fi

                if [[ -z "$vendor_out_dir" ]]; then
                    lunch $vendor_lunch 2>&-
                    vendor_out_dir=$ANDROID_PRODUCT_OUT
                fi

                if [[ -z "$system_out_dir" ]]; then
                    lunch $system_lunch 2>&-
                    system_out_dir=$ANDROID_PRODUCT_OUT
                fi

                echo "List lunch config:"
                echo "kernel: $kernel_lunch"
                echo "vendor: $vendor_lunch"
                echo "system: $system_lunch"
                echo "List out dir:"
                echo "kernel: $kernel_out_dir"
                echo "vendor: $vendor_out_dir"
                echo "system: $system_out_dir"
                return 0
                ;;
            *)
                usage $FUNCNAME
                return 128
        esac
        shift
    done

    timer=$(date +%s)
    enter "${cmd_list[@]}" || return $?
    timer="$(date +%s)-$timer"
    echo "total comsumed time: $(date -d@$((timer)) -u +%H:%M:%S)"

    return 0;
}
