format = """
$username\
$hostname\
$directory\
$line_break\
$character"""

scan_timeout = 10

add_newline = false
# move the rest of the prompt to the right
right_format = """
$cmd_duration\
$git_branch\
$git_state\
$git_status\
$time\
$all"""

# right_format = """$git_branch$git_state$git_status$time$all"""

[character]
success_symbol = '[❯](bold yellow)'

[hostname]
ssh_only = false
format = "[@$ssh_symbol$hostname](green) "

[username]
show_always = true
format = "[$user](green)"

[time]
disabled = false
format = ' [$time]($style) '
style = "purple"

[directory]
format = '[$path](blue)[$read_only]($read_only_style) '
read_only = " "
truncation_length = 2

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"
disabled = true

[git_branch]
format = "[${branch}]($style) "
style = "bright-black"

[git_status]
format = '[${ahead_behind}](blue)[${conflicted}](yellow)[${modified}](cyan)[${staged}](green)[${deleted}](red)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count}'
staged = 'A'
deleted = 'D'
modified = 'M'
conflicted = '✕'
up_to_date = '✔'
style = 'bold red'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[status]
disabled = true
symbol = '✘ '

[line_break]
disabled = true
