#!/usr/bin/env bash

trim_slash_end() { echo ${@%/}; }

trim_slash() { echo "$@" | tr -s /; }

trim_path() { trim_slash_end "$(trim_slash "$@")"; }

abs_path() { echo $(realpath -m -s "$@"); }

rel_path() { echo $(realpath -m -s --relative-to=$(pwd) "$@"); }

# usage:
#   $0 file.name /path/to/dir
find_path() {
	local dir file

	file="$1"
	[[ -z "$file" ]] && return 1

	dir="$(abs_path $2)"
	[[ -z "$dir" ]] && return 2

	while true; do
		if [[ -e ${dir}/${file} ]]; then
			echo ${dir}/${file}
			return 0
		fi

		[[ "$dir" == / ]] && break

		dir="$(dirname $dir)"
	done

	return 3
}

# usage:
#   $0 /path/to/file.name => search file.name from assigned wd
#	$0 file.name => search file.name from cwd
find_file_path() { find_path "$(basename $1)" "$(dirname $1)"; }

source_file() { source $(find_file_path "$1"); }

# call the func to get the file path inside the sourced script
source_file_path() { echo "$(readlink -e "$(dirname ${BASH_SOURCE[0]})")"; }
