#!/usr/bin/env bash

__menu_title=
__menu_prompt=
__menu_choice=
__menu_default=
__menu_default_text=
__menu_no_prompt=n

menu_choice() {
	echo $__menu_choice
}

menu_default() {
	__menu_default="$1"
	__menu_default_text="($__menu_default) "
}

menu_title() {
	__menu_title="$@"
}

menu_prompt() {
	__menu_prompt="$@"
}

menu_no_prompt() {
	__menu_no_prompt=y
}

_show_menu() {
	local i item
	i=1
	for item in $@; do
		echo "$((i++))) $item"
	done
}

menu() {
	local item opts i ans

	opts=("$@")

	[[ -n "$__menu_title" ]] && echo "$__menu_title"
	_show_menu $@

	[[ "$__menu_no_prompt" == y ]] && return

	while :; do
		read -p "$__menu_prompt $__menu_default_text" ans
		ans=${ans:-$__menu_default}

		if [[ -z "$ans" ]]; then
			echo "empty input"
		elif [[ ! $ans =~ ^[0-9]+$ ]]; then
			echo "not a number. ($ans)"
		elif (( ans <= 0 || ans >= i )); then
			echo "an illegal value. ($ans)"
		else
			break
		fi
	done

	__menu_choice="${opts[$((ans-1))]}"
}
