#!/usr/bin/env bash

__menu_title=
__menu_prompt=
__menu_choice=
__menu_default=
__menu_default_text=

menu_choice() {
	echo $__menu_choice
}

menu_default() {
	__menu_default="$1"
	__menu_default_text="($__menu_default) "
}

menu_title() {
	__menu_title="$@"
}

menu_prompt() {
	__menu_prompt="$@"
}

menu_show() {
	local i item

	[[ -n "$__menu_title" ]] && echo "$__menu_title"

	for item in $@; do
		echo "$((++i))) $item"
	done
}

menu_select() {
	local item opts i ans

	menu_show $@

	while :; do
		read -p "$__menu_prompt $__menu_default_text" ans
		ans=${ans:-$__menu_default}

		if [[ -z "$ans" ]]; then
			echo "empty input"
		elif [[ ! $ans =~ ^[0-9]+$ ]]; then
			echo "not a number. ($ans)"
		elif (( ans <= 0 || ans >= i )); then
			echo "an illegal value. ($ans)"
		else
			break
		fi
	done

	opts=("$@")
	__menu_choice="${opts[$((ans-1))]}"
}
