#!/usr/bin/env bash

has_cmd() {
    command -v "$1"
    return $?
} &> /dev/null

has_cmds() {
    local cmd num

    num=0
    for cmd in $@; do
        has_cmd $cmd || (( num++ ))
    done

    return $num
} &> /dev/null

in_wsl() {
	if [[ -z "$WSL_DISTRO_NAME" ]]; then
		return 1
	else
		return 0
	fi
}

os_ver() {
	local os

	# 'macOS'
	if has_cmd sw_vers; then
		os="$(sw_vers -productName)"

	# 'Ubuntu'
	elif has_cmd lsb_release; then
		os="$(lsb_release -i)"
		os="${code##*: }"
	fi

	# unsupported os
	# return a null string and error code
	echo $os
} 2> /dev/null

OS_MACOS='macOS'
OS_UBUNTU='Ubuntu'
