PKG_NAME=
CONFIG_DIR=${XDG_CONFIG_HOME}/$(PKG_NAME)

.ONESHELL:
config.$(PKG_NAME):
	$(H)echo "-- setup $(PKG_NAME) config --"

install.$(PKG_NAME):

remove.$(PKG_NAME):

.PHONY: config.$(PKG_NAME) install.$(PKG_NAME) remove.$(PKG_NAME)
