#!/usr/bin/env bash

#
# Create an float terminal window in tmux
#
# NOTE: This script should be used in tmux keybind
#

# detect current session & window name
src_term="$(tmux display-message -p '#S')"
src_wid="tty$(tmux display-message -p '#{window_id}')"

# default session name
ft_term="[FloatTerm]"
ft_conf="${XDG_CONFIG_HOME}/tmux/float-term.conf"

# toggle float terminal here
if [[ "${src_term}" == "${ft_term}" ]]; then
	tmux kill-session
	exit
fi

# create session with assigned .conf
if ! tmux has-session -t ${ft_term}; then
	tmux new-session -f ${ft_conf} -d -c $PWD -s ${ft_term}
	new_term=y
fi

# attach session
# '\;' is used for separating internal tmux command
pop_cmd=("tmux attach-session -t ${ft_term} '\;'")

if [[ "$new_term" == y ]]; then
	# new session would have a new window
	pop_cmd+=("rename-window ${src_wid} '\;'")
else
	ft_win="$(tmux lsw -F '#{window_name}' -t ${ft_term} | grep -w ${src_wid})"
	if [[ -z "$ft_win" ]]; then
		pop_cmd+=("new-window -n ${src_wid} -c $PWD '\;'")
	else
		pop_cmd+=("select-window -t ${ft_win} '\;'")
	fi
fi

# pop up float window
eval tmux popup -w 80% -h 80% -E ${pop_cmd[*]} || true
